[package]
name = "ndtm-rs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "binary"
path = "src/bin.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
